# -*- coding: utf-8 -*-
"""Agent_class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NgEe-2QMPSi9k7C9V8Vdy4s_-bA6LjRB

# Agent class
Basically the actor-critic NN
"""

# importing libraries
import numpy as np
import torch
import torch.nn as nn
from torch.distributions.categorical import Categorical
from torchsummary import summary
import gym
from datetime import datetime

# init layer
def layer_init(layer, std=np.sqrt(2), bias_const=0.0):
  torch.nn.init.orthogonal_(layer.weight, std)
  torch.nn.init.constant_(layer.bias, bias_const)
  return layer

# agent class
class Agent(nn.Module):
  def __init__(self, envs):
      super(Agent, self).__init__()
      self.critic = nn.Sequential(
          layer_init(nn.Linear(np.array(envs.single_observation_space.shape).prod(), 64)),
          nn.Tanh(),
          layer_init(nn.Linear(64, 64)),
          nn.Tanh(),
          layer_init(nn.Linear(64, 1), std=1.0),
      )
      self.actor = nn.Sequential(
          layer_init(nn.Linear(np.array(envs.single_observation_space.shape).prod(), 64)),
          nn.Tanh(),
          layer_init(nn.Linear(64, 64)),
          nn.Tanh(),
          layer_init(nn.Linear(64, envs.single_action_space.n), std=0.01),
      )

  def get_value(self, x):
      return self.critic(x)

  def get_action_and_value(self, x, action=None):
      logits = self.actor(x)
      probs = Categorical(logits=logits)
      if action is None:
          action = probs.sample()
      return action, probs.log_prob(action), probs.entropy(), self.critic(x)

  # NN summary
  def print_summary(self, envs):
    print('Actor summary')
    print(summary(self.actor, envs.single_observation_space.shape))
    print('Critic summary')
    print(summary(self.critic, envs.single_observation_space.shape))

  def get_parameters(self):
    #useful if wanting to check the updating of NN parameters
    for name, param in self.named_parameters():
      print(name, param.data)

  # checkpoints
  def get_checkpoint_name(epoch_v):
    now = datetime.now()
    today = now.strftime("%Y_%m_%d_%H_%M_%S")
    check_name = 'checkpoint' + '_' + str(epoch_v) + '_' + today
    return check_name

  def checkpoint(self, epoch_v):
    checkpoint_name = get_checkpoint_name(epoch_v)
    path = os.getcwd() + '/' + checkpoint_name
    torch.save(self, path)

  def resume_from_checkpoint(self, path):
    print("=> loading checkpoint '{}'".format(path))
    return torch.load(path)



