# -*- coding: utf-8 -*-
"""environment_creator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Gaianeve/PPO/blob/main/environment_creator.ipynb

# Environment file
This is the file that will actually contain the environment, and make it. For now, let's just make the environment
"""

# importing libraries
import os
import gym

# making the environment
def make_env(gym_id, seed, idx, capture_video, run_name):
    def thunk():
        env = gym.make(gym_id)
        env = gym.wrappers.RecordEpisodeStatistics(env)
        if capture_video:
            if idx == 0:
                env = gym.wrappers.RecordVideo(env, f"videos/{run_name}")
        env.seed(seed)
        env.action_space.seed(seed)
        env.observation_space.seed(seed)
        return env

    return thunk

# vectorize environment
def vectorize_env(gym_id, seed, capture_video, run_name, num_envs):
  envs = gym.vector.SyncVectorEnv(
        [make_env(gym_id, seed + i, i, capture_video, run_name) for i in range(num_envs)]
  )
  assert isinstance(envs.single_action_space, gym.spaces.Discrete), \
  "only discrete action space is supported"
  return envs

